global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'whisper'
    static_configs:
      - targets: ['whisper:9000']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']

  - job_name: 'flowise'
    static_configs:
      - targets: ['flowise:3001']

  - job_name: 'open-webui'
    static_configs:
      - targets: ['open-webui:8080']

# Created and maintained by Z4Y 